UCLALibrary/libraryweb-site

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
@akohler does as title suggests... please deploy. https://jira.library.ucla.edu/browse/OP-636
> OP-636: fixes Databases A-Z link on home page search widget

- www/sites/all/modules/contrib/admin_views/LICENSE.txt
- www/sites/all/modules/contrib/admin_views/admin_views.css
- www/sites/all/modules/contrib/admin_views/admin_views.info
- www/sites/all/modules/contrib/admin_views/admin_views.install
- www/sites/all/modules/contrib/admin_views/admin_views.module
- www/sites/all/modules/contrib/admin_views/admin_views.views.inc
- www/sites/all/modules/contrib/admin_views/admin_views.views_default.inc
- www/sites/all/modules/contrib/admin_views/admin_views_default/book.admin-content-book.inc
- www/sites/all/modules/contrib/admin_views/admin_views_default/comment.admin-content-comment.inc
- www/sites/all/modules/contrib/admin_views/admin_views_default/node.admin-content.inc
- www/sites/all/modules/contrib/admin_views/admin_views_default/taxonomy.admin-content-taxonomy.inc
- www/sites/all/modules/contrib/admin_views/admin_views_default/user.admin-people.inc
- www/sites/all/modules/contrib/admin_views/plugins/views_plugin_access_menu.inc
- www/sites/all/modules/contrib/admin_views/plugins/views_plugin_display_system.inc
- www/sites/all/modules/contrib/admin_views/tests/admin_views.test
- www/sites/all/modules/contrib/admin_views/tests/admin_views_test/admin_views_test.info
- www/sites/all/modules/contrib/admin_views/tests/admin_views_test/admin_views_test.module
adds admin_views module for added sanity when working with Drupal content and users - https://www.drupal.org/project/admin_views
I'm usually for removing uneeded modules, but I feel that with a site of our size this module will be a great help for those maintaining the content and users on the the site. 
@akohler please deploy to www-test so we can evaluate it next week. I expect everything to go well and we can use this in production in near future releases.
> Addition of admin_views module

- www/sites/all/modules/contrib/views/drush/views.drush.inc
- www/sites/all/modules/contrib/views/handlers/views_handler_filter_date.inc
- www/sites/all/modules/contrib/views/includes/cache.inc
- www/sites/all/modules/contrib/views/modules/comment/views_plugin_row_comment_rss.inc
- www/sites/all/modules/contrib/views/modules/node/views_plugin_row_node_rss.inc
- www/sites/all/modules/contrib/views/plugins/views_plugin_cache.inc
- www/sites/all/modules/contrib/views/plugins/views_plugin_display.inc
- www/sites/all/modules/contrib/views/plugins/views_plugin_display_attachment.inc
- www/sites/all/modules/contrib/views/plugins/views_plugin_query_default.inc
- www/sites/all/modules/contrib/views/tests/handlers/views_handler_filter_date.test
- www/sites/all/modules/contrib/views/tests/views_groupby.test
- www/sites/all/modules/contrib/views/tests/views_module.test
- www/sites/all/modules/contrib/views/tests/views_test.info
- www/sites/all/modules/contrib/views/views.api.php
- www/sites/all/modules/contrib/views/views.info
- www/sites/all/modules/contrib/views/views_ui.info
@z3cka I think we should push this security update to production this weekend.  OK to proceed?
See release notes for other changes: https://www.drupal.org/node/2480259
> DRUP-688: Upgraded from 7.x-3.10 to 7.x-3.11

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
* also removes some uneeded spacing in the code
@akohler this one is better than #59.
> WS-412: #ready #comment changes link on the Databases tab "Find Databases by Subject" on the home page

- www/sites/all/modules/custom/ucla_search/includes/ucla_search_handlers.inc
- www/sites/all/modules/custom/ucla_search/ucla_search.info
@akohler please pull to www-test w/ regular master workflow.
> OP-745: changes search endpoint back on Research Guides tab

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
> WS-453: #ready – removes title from search for a database search widget placeholder

- www/sites/all/modules/features/uclalib_exhibition/plugins/content_types/exhibition_dates.inc
@akohler this can wait for this weekend's deployment
> added missing closing tag </i> to exhibitions page

- www/sites/all/themes/uclalib_omega/uclalib_omega.info
@akohler please merge and deploy to test.
> OP-757: #ready removes qualaroo javascript as we no longer need this service

- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.info
- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.module
@akohler please pull to ```www-test```.
> DRUP-741: #ready Fixes Wrong Username on ORCID batch user creation

- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.info
- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.module
@akohler please deploy to prod this weekend as it has been QA'ed on ```www-test```.
> DRUP-741: #close Fixes Wrong Username on ORCID batch user creation

- www/sites/all/modules/contrib/article_discovery/Summon.class.php
This is needed for testing the article_discovery module. This will someday go in during this build instead of our repo, but this is fine for now.
> DRUP-757: adds Summon.class.php library

- www/sites/all/modules/contrib/orcid_integration/orcid_integration.info
- www/sites/all/modules/contrib/orcid_integration/orcid_integration.module
- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.info
- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.module
- www/sites/all/modules/custom/orcid_integration_extras/orcid_integration_extras.info
- www/sites/all/modules/custom/orcid_integration_extras/orcid_integration_extras.module
includes: name enhancements, user shiboleth integration and flag new users that may have an ORCID account with a private email. 
@akohler please deploy tonight if possible. Thank you!
> DRUP-761: #Verified adds aditiona ORCID batch tweaks that I missed on last depolyment

- www/sites/all/modules/features/uclalib_staff_profile/css/staff_profile_extras.css
OP-313_vendor-padding fixes css bug that not all browsers handle ul indent the same reset to padding 0, margin 0
@z3cka please deploy to test, thanks!
> OP-313: Adding vendor prefix padding 0 webkit

- www/sites/all/modules/contrib/orcid_integration/orcid_oauth/orcid-oauth-thankyou.tpl.php
- www/sites/all/modules/contrib/orcid_integration/orcid_oauth/orcid_oauth.module
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
looks like I forgot to PR this last week.
> DRUP-763: updates ORCID thank you page with new copy

- www/sites/all/modules/features/uclalib_staff_profile/css/staff_profile_extras.css
#143 was missing some of the css tweaks.
> sorry about that! css fixes module description to show

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_staff_profile.scss
@z3cka This should do it. I am not expecting any more changes. Please merge and copy to www-test. Thanks!
> changes to css column widths

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_staff_profile.scss
@z3cka kind of a priority, staff profile caused all bullet lists to be bulletless
> Staff profile bullet list fix2

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
@z3cka this seemed to easy, I prolly did something wrong
> OP-828 priority fix bullet list fix to show bullets

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.features.inc
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
@z3cka Can you merge this to test? Apparently I forgot to test for the most important feature: being able to search by donor name! Thanks!
> DRUP-802 adds author and donor name to search index

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_pane-page-title.scss
@z3cka plz merge to test, thx buddy
> OP-834: increased padding top 5 px on gray bar

- www/sites/default/test.settings.php
@z3cka I'll do this merge and deploy now.
> DRUP-843: Point www-test to new solr test system

- www/sites/all/modules/custom/rc_res/rc_res.module
I added some text to one rc-res page.
> WS-686_add_msg: add message to the Reseach Commons page

- www/sites/all/modules/custom/rc_res/rc_res.module
These are ready for evaluation on www-test.
> squashed WS-689 and WS-690

- www/sites/all/modules/custom/rc_res/rc_res.info
- www/sites/all/modules/custom/rc_res/rc_res.module
WS-709: Add anouncements and email update to rc-res, squashes commits from ws-686, ws-689, ws-690
> WS-709: Add anouncements and email update to rc-res

- www/sites/all/modules/custom/ucla_search/includes/ucla_search_handlers.inc
- www/sites/all/modules/custom/ucla_search/ucla_search.info
- www/sites/all/modules/custom/ucla_tab_search/articleplus_articles_container_mel_description.tpl.php
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_hp_tabbed_search.scss
Squashed commits include (redundant merge commits not listed):
commit 752412d747cd717d238ce28aba35dbb7bc51a8c2
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Thu Mar 3 10:56:32 2016 -0800
DRUP-819: adds scss file for homepage css to resize AP graphic, optimizes SVG code in template file
commit bbd8fb6ebb65020cc77820b7337ad6cd9daff5cd
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Thu Mar 3 21:12:31 2016 +0000
fixes undefined index 'render element' php notice that Andy found
commit 7997af508f6ff4726a3d0f71d43b48405cd216b0
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Thu Mar 3 05:58:23 2016 +0000
adds svg image to search widget via #theme; requires a bit more css work
commit 287e68ca3961eb5af99d2cf88a13092514161cf7
Author: Andy Kohler …
> Version 7.x-1.5-beta2 of tabbed search.

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_pane-give-now-button.scss
@z3cka plz merge to test and Allison will follow up with Dawn Setzer
> OP-831: adds padding-top

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_pane-ucla-tab-search-ucla-tab-search-tabs.scss
@z3cka plz merge to www-test, thanks!
> DRUP-860: adds text-indent: 7px to tabbed search on homepage

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.module
@z3cka new commit, ready to merge to test.
> DRUP-802: replaces 'access arguments' with correct value

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
@z3cka Please review and merge to www-test.
> DRUP-858: #ready Add accessibility labels to designated controls on tabbed search form

- www/sites/all/modules/custom/ucla_search/includes/ucla_search_handlers.inc
- www/sites/all/modules/custom/ucla_search/includes/ucla_search_logger.inc
- www/sites/all/modules/custom/ucla_search/ucla_search.info
- www/sites/all/modules/custom/ucla_search/ucla_search.install
- www/sites/all/modules/custom/ucla_search/ucla_search.views.inc
- www/sites/all/modules/custom/ucla_search/views/search_log_data.inc
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.js
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_hp_tabbed_search.scss
- www/sites/all/themes/uclalib_omega/sass/components/_pane-ucla-tab-search-ucla-tab-search-tabs.scss
Upgrades ucla_tab_search and ucla_search to 7.x-1.5.
Requires one database update.
commit d4317458776dc5b16ad6b02fd70eafa458785621
Date:   Thu Mar 24 09:36:06 2016 -0800
DRUP-813: Remove beta from version numbers, ready for release
commit 5697ebd4d48e4f28ffe3caa55141796a6b117e59
Date:   Mon Mar 21 21:31:42 2016 -0800
Version 7.x-1.5-beta5 of ucla_search.
Adds 3 columns for logging form elements not used on all tabs:
* search code (UCLA Library Catalog index code)
* search limit (Summon ArticlesPlus peer review limit)
* search type (UCelinks/SFX/Catalog contains/startswith/exact)
Requires database update, and possibly reversion of
search_log_data view.
commit …
> DRUP-811: Deployment package for ArticlesPlus and other tabbed search changes.

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
commit 83f36e7fbabfd25b67985bc281f12c8b4d067762
Date:   Tue Mar 29 13:57:15 2016 -0800
First beta version for ucla_tab_search
commit d25aaecb53ebf7b8c62dfbf4aac69a8aaba3f196
Date:   Tue Mar 29 13:52:39 2016 -0800
DRUP-858: Add labels to Journals select inputs
commit ebf2ab1a183af506584fccbef56918f53dcdfea7
Date:   Tue Mar 29 13:43:28 2016 -0800
DRUP-883: Change link from ArticlesPlus description to go to Summon
> Version 7.x-1.6-beta1 of tabbed search.

- www/sites/all/modules/custom/ucla_shib_extras/ucla_shib_extras.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/features/uclalib_system/uclalib_system.info
commit afa399fd67b50ce6d7a2185ed62d89545e285a7d
Date:   Thu Mar 31 11:33:30 2016 -0800
DRUP-865: Bump version for prod release
commit d36e1a90808aac3bcb697cababf716ded5eb375a
Date:   Thu Mar 31 11:32:15 2016 -0800
DRUP-858: Bump version for prod release
commit 7c20be6985d13867c41f26fdee366f0fac9bc4dc
Date:   Thu Mar 31 11:31:15 2016 -0800
DRUP-882: Bump version for prod release
> Remove beta from versions for release to production.

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
commit 647c0fbf2b212ef18ea484fe7f2d01484c822b5e
Date:   Thu Mar 31 11:32:15 2016 -0800
DRUP-858: Bump version for prod release
commit 57ddb93c05d66cf63a3fb6048f0754597578882a
Date:   Tue Mar 29 13:58:30 2016 -0800
Version 7.x-1.6-beta1 of tabbed search.
commit 83f36e7fbabfd25b67985bc281f12c8b4d067762
Date:   Tue Mar 29 13:57:15 2016 -0800
First beta version for ucla_tab_search
commit d25aaecb53ebf7b8c62dfbf4aac69a8aaba3f196
Date:   Tue Mar 29 13:52:39 2016 -0800
DRUP-858: Add labels to Journals select inputs
commit ebf2ab1a183af506584fccbef56918f53dcdfea7 …
> Version 7.x-1.6 of ucla_tab_search for deployment.

- www/sites/all/modules/features/uclalib_system/plugins/content_types/search_form.inc
- www/sites/all/modules/features/uclalib_system/uclalib_system.info
commit 65e0eefb5ad625fee8ef526a7482662b6a21ab97
Date:   Thu Mar 31 11:33:30 2016 -0800
DRUP-865: Bump version for prod release
commit d695456bf01786833e611a9e6b20868bc7d80e4f
Date:   Tue Mar 29 14:27:52 2016 -0800
DRUP-865 #ready Add accessibility label to Site Search box
> Version 7.x-1.1 of uclalib_system for deployment.

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.views_default.inc
@z3cka DRUP-895: fixes blurry images in taxonomy filters if only one image on page, updates version #
> Drup-895: detailed commit messages in PR

- www/sites/all/modules/custom/site_alert/site_alert.module
plz review. I can deploy unless @akohler wants to do it.
> DRUP-925: #ready allow br tag in site alert

- www/sites/all/modules/custom/site_alert/site_alert.module
> DRUP-925: #awaiting allow br tag in site alert

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.views_default.inc
@z3cka sorry, I missed this, but it's very obviously bad typo, plz merge to test. thanks!
> DRUP-895: #ready fixes type "make" should be "made" in view

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.views_default.inc
@z3cka plz merge to test and I will add to DRUP-967 (out-of-cycle deployment) ticket. thx.
> DRUP-895: Bookplates, views removes filter published

- www/sites/all/modules/custom/schedule_source/schedule_source.module
Web Clicc Clock-In Kiosk requests from unregistered ip's will now redirect to a landing page with directions for help
> MAINT-1849 Web Clock-In Kiosk - added landing page for unregistered IPs

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.features.fe_block_settings.inc
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
@z3cka plz merge to www-test thx!
> manual removal of unused 'sort by subject area' block

- www/sites/all/themes/uclalib_omega/css/layouts/homepage/homepage.layout.css
- www/sites/all/themes/uclalib_omega/sass/layouts/homepage/homepage.layout.scss
@z3cka can you merge this to www-test this week so Juan can continue his work on the hompage revamp? thx!
> DRUP-997: #ready enlarges link-list icons for homepage ONLY

- www/sites/all/modules/features/uclalib_homepage/uclalib_homepage.info
- www/sites/all/modules/features/uclalib_homepage/uclalib_homepage.pages_default.inc
- www/sites/all/themes/uclalib_omega/css/layouts/homepage/homepage.layout.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.normalize.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/layouts/homepage/homepage.layout.scss
@z3cka I based this off our master branch. Please merge to test when you get a chance -- no rush.
> DRUP-997: #ready updates css and panels for equipment box on homepage

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.normalize.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/regions/_header.scss
- www/sites/all/themes/uclalib_omega/sass/regions/_navigation.scss
made area scrollable, fixed border on menu trigger
Can't see any obvious reason why my compile is using 6 character values instead of three...
> UCLALIB-266: Fixed height of colophon menus

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
@z3cka I am merging this, changes dot info file to 2.7-beta1 for test
> bookplates preps info file for fixing missing commit

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.facetapi_defaults.inc
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.features.fe_block_settings.inc
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.views_default.inc
@z3cka please merge to www-stage
> DRUP-1033: applies missing commits for bookplates

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.pages_default.inc
@z3cka syncing master with stage (features re-rolled from prod), plz merge, thx!
> DRUP-1043: #ready adds mobile css and menu title

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_staff_profile.scss
@z3cka this is part of the effort to kill off zombie tickets.... plz merge
> OP-871: #ready css deletes css that was not being used and causing issues on site

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_staff_profile.scss
@z3cka will make a deploy ticket for this...
> OP-871: #ready css delete css that was not being used

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_pane-ucla-tab-search-ucla-tab-search-tabs.scss
@z3cka I will make an out of cycle deployment ticket for this.
> OP-882: #ready fixes keyword drop not appearing changes to css

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_pane-ucla-tab-search-ucla-tab-search-tabs.scss
@z3cka this is ready to go to stage
> OP-882 #awaiting fixes keyword dropdown with css

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_pane-give-now-button.scss
@z3cka pretty simple change. I rebased from master so hopefully you won't have conflicts. Can you review/merge/copy to test while I am on vacation? I will add to Project. Many thx!
> DRUP-1147: adds padding left to give now button

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_pane-opening-hours-table.scss
@z3cka plz close your PR and use this one, thanks!
> DRUP-1155: #ready changes table header from dark gray to white and bold

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_bookplates.scss
@z3cka plz merge when you get a chance, thx
> Urgent css (no ticket) nth+3 width 33% and font size bumped up to 16px

- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_bookplates.scss
@z3cka cherry-picked, ready for merge to staging, will add PR to ticket.
> DRUP-1188: Out of cycle deployment css fixes for Bookplates

- www/sites/all/modules/features/uclalib_navigation/plugins/ctools/content_types/uclalib_nav.inc
- www/sites/all/themes/uclalib_omega/js/mobile-collapsible.js
@z3cka is this a hack? (it works) Please review
> DRUP-1247: #Ready fixes accessibility alert redundant link

- www/sites/all/modules/contrib/node_clone/LICENSE.txt
- www/sites/all/modules/contrib/node_clone/README.txt
- www/sites/all/modules/contrib/node_clone/clone.api.php
- www/sites/all/modules/contrib/node_clone/clone.info
- www/sites/all/modules/contrib/node_clone/clone.install
- www/sites/all/modules/contrib/node_clone/clone.module
- www/sites/all/modules/contrib/node_clone/clone.pages.inc
- www/sites/all/modules/contrib/node_clone/clone.rules.inc
- www/sites/all/modules/contrib/node_clone/views/clone.views.inc
- www/sites/all/modules/contrib/node_clone/views/views_handler_field_node_link_clone.inc
> DRUP-1254: #ready adds module node clone

- www/sites/all/modules/contrib/node_clone_tab/LICENSE.txt
- www/sites/all/modules/contrib/node_clone_tab/node_clone_tab.info
- www/sites/all/modules/contrib/node_clone_tab/node_clone_tab.module
> DRUP-1254: #ready adds additional module clone node tab for UI

- www/sites/default/prod.settings.php
- www/sites/default/stage.settings.php
- www/sites/default/test.settings.php
This deploys the configs for pointing at the new solr cluster tonight at 10pm.
> DRUP-1186: #awaiting points to new solr cluster

- www/sites/all/modules/custom/statsform/statsform.module
- www/sites/all/modules/custom/statsform/templates/page--hijacked.tpl.php
- www/sites/all/modules/custom/statsform/templates/page--hijackedLogin.tpl.php
This is a new branch made off my development master after fetching upsteam.
It updates authentication and adds a comment box.
> refined authentication; added comments box to Research Assistance

- www/sites/all/modules/custom/statsform/statsform.module
Used check_plain() to sanitize the data from the user.
The data then passes on to the Web Service.
> WS-960k - sanitized form data that is passed on to the Web Service

- www/sites/all/modules/custom/statsform/templates/page--hijacked.tpl.php
- www/sites/all/modules/custom/statsform/templates/page--hijackedLogin.tpl.php
Minor fix and update; please deploy to www-test once approved.
> fixed submit button disable on Research Assistance; updated labels

- www/sites/all/modules/custom/statsform/templates/page--hijackedLogin.tpl.php
Simple wording change
Please deploy to www-test when possible - thanks!
> WS-960p - updated label on popup

- www/PATCHES.txt
- www/sites/all/modules/contrib/references_dialog/css/references-dialog-admin.css
- www/sites/all/modules/contrib/references_dialog/js/references-dialog.js
- www/sites/all/modules/contrib/references_dialog/references_dialog.dialog_widgets.inc
- www/sites/all/modules/contrib/references_dialog/references_dialog.info
- www/sites/all/modules/contrib/references_dialog/references_dialog.module
This also removes the need for an old patch that was being used.
> DRUP-1278: Updates references_dialog from 7.x-1.0-alpha4+11-dev to 7.x-1.0-beta2

- www/sites/all/modules/custom/statsform/templates/custom.tap.js
- www/sites/all/modules/custom/statsform/templates/page--hijacked.tpl.php
- www/sites/all/modules/custom/statsform/templates/page--hijackedLogin.tpl.php
Fixed bugs, rest of the modals are now centered, enhanced experience for tablet users
> remaining modals fix & buttons fix

- www/sites/all/modules/custom/statsform/statsform.module
- www/sites/all/modules/custom/statsform/templates/page--hijacked.tpl.php
Added code to process the Referral checkbox
> Ws 1372 submission bug

- www/sites/all/modules/custom/statsform/templates/page--hijacked.tpl.php
Added two links to Reports for evaluation
1. Opens in new tab
2. Opens a new window (size can be set in code)
> WS-1367 - Added two links to Reports for evaluation
