UCLALibrary/libraryweb-site

- www/sites/all/modules/contrib/orcid_integration/includes/orcid_integration.pages.inc
- www/sites/all/modules/contrib/orcid_integration/orcid_integration.module
- www/sites/all/modules/custom/orcid_integration_extras/orcid_integration_extras.info
- www/sites/all/modules/custom/orcid_integration_extras/orcid_integration_extras.module
- www/sites/all/modules/custom/orcid_redirect/orcid_redirect.info
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_form_orcid.scss
DRUP-663: improves usabiity by changing "Posible Matches" to "Search for Existing Account by Email" via DRUP-665
DRUP-663: Surpresses "orchid ID is not set up" message, DRUP-666: fixes account mapped copy, DRUP-667: changes confrmation screen to go to user view
DRUP-663: hides the ORCID field on the user edit form (aka user_profile_form) via: DRUP-668
adds version and package group to orcid_integration module
DRUP-669 adds unlink ORCID button and functionality
> DRUP-663: adds usability ORCID form edits

- www/sites/all/modules/custom/default_opening_hours/default_opening_hours.module
@z3cka You asked about this - at present, just a hard-coded date in the default_opening_hours custom module from Bluespark.  Go ahead and merge, please.
I considered doing an administrative interface for this, but since we're extending the current allowable dates to 2016 and our new hours project should be done long before that... not worth the effort to do an admin module for the current system.
> OP-725: Extended allowable dates to June 30 2016

- www/.gitignore
- www/sites/default/settings.php
@darrowcoucla and @z3cka : Cleanup from yesterday's problem caused settings.php to be removed from the repo, because www/.gitignore excluded it.  I've updated .gitignore so it's no longer excluded, and re-added settings.php to the repo.  I'll merge this pull request and deploy ASAP to reduce risk of further problems.
> DRUP-676: Re-added settings.php after removing from .gitignore

- www/sites/all/modules/contrib/orcid_integration/includes/orcid_integration.pages.inc
- www/sites/all/modules/contrib/orcid_integration/orcid_integration.info
- www/sites/all/modules/contrib/orcid_integration/orcid_oauth/orcid-oauth-connect.tpl.php
- www/sites/all/modules/contrib/orcid_integration/orcid_oauth/orcid-oauth-connected.tpl.php
- www/sites/all/modules/contrib/orcid_integration/orcid_oauth/orcid-oauth-thankyou.tpl.php
- www/sites/all/modules/contrib/orcid_integration/orcid_oauth/orcid_oauth.info
- www/sites/all/modules/contrib/orcid_integration/orcid_oauth/orcid_oauth.module
* interacts with orcid_integration (new dependency) module by modifying form
* various code cleanup and prep for eventual move to be a sub-module of orcid_integration
pc = cherry-picked
DRUP-675: moved orcid_oauth module inside of orcid_integration module
@akohler please deploy to test and prod. These involve new modules that are safe to go to prod in code. Will turn on in prod after a bit more testing in www-test.
> DRUP-675: #ready makes ORCID api calls with variables from configuration

- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.info
- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.module
- www/sites/all/modules/custom/orcid_integration_extras/orcid_integration_extras.info
- www/sites/all/modules/custom/orcid_integration_extras/orcid_integration_extras.module
This PR contains 2 commits:
1. DRUP-741: revisits the wrong name issue and fixes it better than...
f2f5fcfc7063a7436ae43650dcabea353c95bba1 did by passing the data to hook_user_presave() is a custom UCLA specific module rather than the main orcid module.
2. DRUP-746: #ready shib-o-lize's drupal user accounts created via ORCID batch script
by updating some of shib_auth's tables while the users are saved during the batch
@akohler please deploy to ```www-test```. 
I will then test by creating a new Drupal user via the ORCID batch process and then attempt to login to ```www-test``` via shib_auth with said new user.
> DRUP-746: #ready shib-o-lize's drupal user accounts created via ORCID batch script

- www/sites/all/modules/features/uclalib_users/uclalib_users.module
I will doploy this along with #116
> DRUP-766: #ready removes the "Member for:" data on the User page

- www/sites/all/modules/contrib/orcid_integration/orcid_integration.info
- www/sites/all/modules/contrib/orcid_integration/orcid_integration.module
- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.info
- www/sites/all/modules/contrib/orcid_integration/orcid_integration_provision/orcid_integration_provision.module
- www/sites/all/modules/contrib/orcid_integration/orcid_oauth/orcid-oauth-thankyou.tpl.php
- www/sites/all/modules/contrib/orcid_integration/orcid_oauth/orcid_oauth.module
- www/sites/all/modules/custom/orcid_integration_extras/orcid_integration_extras.info
- www/sites/all/modules/custom/orcid_integration_extras/orcid_integration_extras.module
- www/sites/all/modules/features/uclalib_users/uclalib_users.module
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
Squashed commits include:
1. DRUP-766: removes the "Member for:" data on the User page
2. DRUP-746: #ready shib-o-lizes users properly now; DRUP-764: #ready removes debug statments
3. DRUP-763: updates ORCID thank you page with new copy
Ready for this week's deployment.
> DRUP-578: #ready includes final changes for all sub-tickets

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
This fixes problems with the tabbed search form submission procedure, which relied on the Drupal "tabs__active_tab" and the value of the Submit button for each "form" within the uber-form.
When form tabs are accessed directly via url hash fragments, tabs__active_tab remains at the default, the first "Books" form.  Also, depending on whether the user clicks the "Search" button or presses enter, the submitted form data varies such that the value of the Submit button is no longer reliable.
The handler now looks for a non-empty "text_query" field, which is required (semantically, if not technically...) on each form.  This is used to identify the active tab/form, so that the search is correctly logged and routed to the appropriate remote system to execute.
@z3cka : Please review and …
> DRUP-811: Fix form handler problem caused by url hash fragments

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
I reworked the form submission logic to take both tabs__active tab (Drupal's sometimes-wrong value for which tab is active) and text_query (which has real submitted data, but can have multiple occurrences due to our compound form) into account.
If both sources agree, that's the real tab and the corresponding data is handled.
If the sources disagree (e.g., tab was accessed directly via url#hash), we trust the submitted text_query.  However, we have to loop through all tab data before making a decision, since we could first have a mismatch, then later a real match.
So now, instead of looping through all tabs and making a decision based on the first match, the code loops through all tabs to collect information to make the right decision, then moves forward with that data.
@z3cka Please …
> DRUP-811: Fix problem with naive handling of text_query when back button is used

- www/sites/all/modules/custom/ucla_search/includes/ucla_search_logger.inc
- www/sites/all/modules/custom/ucla_search/ucla_search.info
- www/sites/all/modules/custom/ucla_search/ucla_search.install
- www/sites/all/modules/custom/ucla_search/ucla_search.views.inc
- www/sites/all/modules/custom/ucla_search/views/search_log_data.inc
Adds 3 columns for logging form elements not used on all tabs:
* search code (UCLA Library Catalog index code)
* search limit (Summon ArticlesPlus peer review limit)
* search type (UCelinks/SFX/Catalog contains/startswith/exact)
Requires database update, and possibly reversion of
search_log_data view.
commit 2a11089519680bf82e062f0cbb5ce2ba5efd5543
Date:   Mon Mar 21 21:27:03 2016 -0800
DRUP-873: Increment ucla_search version
commit e2e084ddf562a17e26b2488facd57ecf55cfde27
Date:   Mon Mar 21 21:14:46 2016 -0800
DRUP-873: Add new database columns to views; change default sort to date descending
commit 9e133aef4dcdf8d2ccc262f4a9fe4128ef117dd4
Date: …
> DRUP-873 #ready Version 7.x-1.5-beta5 of ucla_search.

- www/sites/all/modules/features/uclalib_news/uclalib_news.module
> hot fix for missing ')'

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/sass/components/_pane-ucla-tab-search-ucla-tab-search-tabs.scss
- www/sites/all/themes/uclalib_omega/sass/components/_vertical-tabs.scss
commit 78e677152397dfbb8a3495fb420352f5e66db078
Author: Casey Grzecka <c@sey.gr>
Date:   Wed Nov 9 09:59:14 2016 -0800
Replaces PR #355 (#359)
OP-882: #ready fixes conflicts for replacing search button with search icon – Replaces PR #355
commit 0050ba52fb4c54c004428503f809991c71524881
Author: EB <elaineblakeman@library.ucla.edu>
Date:   Thu Oct 27 16:05:20 2016 -0700
OP-852: #ready OP-882: #ready adds link for Journal tab and swaps out… (#352)
* OP-852: #ready OP-882: #ready adds link for Journal tab and swaps out search button for search icon
* bumps version to 7.x-1.7-beta1
> OP-882: #awaiting replaces search button with search icon

- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info
- www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.module
@z3cka Please review and merge/deploy to www-test.
Note that I had to add a hook_update_N function, thus requiring database update.  I tried just changing the variable default values in uclalib_bookplates_admin but apparently those only apply when using the admin form itself, and we need the values to be set automatically.  Unfortunately this results in these 2 variable values being hard-coded in two places, which seems quite wrong... feel free to revise or to point me in the correct direction.
I bumped the version from beta1 to beta2 in the info file, hope I remembered that correctly.
Thanks --Andy
> DRUP-1142: Update variables for Catalog linking from bookplate pages

- www/sites/all/modules/features/uclalib_system/plugins/content_types/meta_social.inc
- www/sites/all/modules/features/uclalib_system/plugins/content_types/templates/uclalib-system-meta-social.tpl.php
- www/sites/all/modules/features/uclalib_system/uclalib_system.info
- www/sites/all/modules/features/uclalib_system/uclalib_system.module
* DRUP-1124: #ready adds text to social links
This was done by switching to a more robust library
commit 2c542926e76081a94117eba8d64b733397b2c08c
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Thu Jan 19 07:06:39 2017 +0000
DRUP-1124: changes order of share icons, email icon to envelope, and minor secletor change and jQuery syntax
commit de11198e009ace4abedebae7a496d07bc94e0752
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Thu Jan 19 06:19:18 2017 +0000
DRUP-1124: moves template to template file and loads external js/css via attached property
commit 0883a8ce7c7bf9ebd4abed528bf8d5ca05a949fb
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Wed Jan 18 19:52:52 2017 +0000
DRUP-1124: WIP on using jssocials to replace addthis TODO: remove nasty inline template
* …
> DRUP-1124: #awaiting adds text to social links

- www/sites/all/modules/custom/ucla_libhours/ucla-libhours-hours.tpl.php
This was due to javascript rendering the user's day on the date provided adjusted for their timezone. The desired day of the week is that actual day of that date. This was achieved by forcing javascript to use UTC for the timezone by passing true as the third parameter to the dateFormat() function. This is documented here: http://blog.stevenlevithan.com/archives/date-time-format
_Oh the joys of javascript!_
> DRUP-1262: #ready fixes the data-label for location hours tables

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
@z3cka Here's a minor change to bring the website's homepage search module into sync with Catalog changes done on VBT-1002.
I bumped the module version up to 1.8, hope that's OK.
Please deploy to test when you get a chance.  I'll do a quick test, and then this can go to production whenever.  Nothing's broken for this in prod now... this just fixes a long-standing problem.
Thanks --Andy
> DRUP-1297: Use left-anchored ISBL index for ISBN searches in Catalog

- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.info
- www/sites/all/modules/custom/ucla_tab_search/ucla_tab_search.module
@z3cka I think this is ready for deployment to production, thanks.
> DRUP-1297: Use left-anchored ISBL index for ISBN searches in Catalog #awaiting

- www/sites/all/modules/features/uclalib_staff_directory/uclalib_staff_directory.views_default.inc
@akohler This was a one line config change in the view config.  
Review here:
https://drup-1318-staff-by-link-7n57cei-sopc3ixpdigl4.us-2.platformsh.site/arts/staff
http auth: uclalib2018 / uclalib2018
> DRUP-1318: Link to department on staff by location view

- www/sites/all/modules/features/uclalib_news/uclalib_news.views_default.inc
- www/sites/all/modules/features/uclalib_quick_find/uclalib_quick_find.views_default.inc
- www/sites/all/modules/features/uclalib_resources/uclalib_resources.pages_default.inc
- www/sites/all/modules/features/uclalib_resources/uclalib_resources.views_default.inc
- www/sites/all/modules/features/uclalib_upcoming_events/uclalib_upcoming_events.features.field_base.inc
- www/sites/all/modules/features/uclalib_upcoming_events/uclalib_upcoming_events.features.field_instance.inc
- www/sites/all/modules/features/uclalib_upcoming_events/uclalib_upcoming_events.info
- www/sites/all/modules/features/uclalib_upcoming_events/uclalib_upcoming_events.module
- www/sites/all/modules/features/uclalib_upcoming_events/uclalib_upcoming_events.views_default.inc
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css
- www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css
- www/sites/all/themes/uclalib_omega/package-lock.json
- www/sites/all/themes/uclalib_omega/sass/components/_more-link.scss
- www/sites/all/themes/uclalib_omega/sass/components/_upcoming-events.scss
This PR fixes the broken "more" links on the News tab on Destinations and Locations:
Steps to review:
1) Visit a Location page, Eg. https://drup-1084-views-more-42glrty-sopc3ixpdigl4.us-2.platformsh.site/sel
2) Scroll down to the News block and click "More"
3) Ensure you're redirected to the /news page with the correct pre-filtered Location in the sidebar facets.
1) Visit a Destination page Eg https://drup-1084-views-more-42glrty-sopc3ixpdigl4.us-2.platformsh.site/destination/research-commons
2) Scroll down to the News block and click "More"
3) Ensure you're redirected to the /news page with the correct pre-filtered Location based on the destination in the sidebar facets.
Other things that were changed in this feature:
* The solution moves the more link out of the footer, from the views …
> DRUP-1084: views more links

- www/sites/all/modules/features/uclalib_staff_directory/uclalib_staff_directory.views_default.inc
An imperfect solution that gets us close to the desired effect sorting results by relevance then by first letter of last name.  Adding a more thorough solution whereby the alpha sort takes into account the fullname by "first, last" would be a non-trivial additional effort, with a new custom field, and a full solr reindex.
Environment link: 
https://drup-1314-staff-search-luhvimy-sopc3ixpdigl4.us-2.platformsh.site/staff?search_api_views_fulltext=charles
> DRUP-1314: Staff Search sort by relevance, then first letter of last name
